### ISSUE TITLE
project support / python3 support

### ISSUE THREAD

**Issue by tbugfinder** [ecmwf/kronos#1]
Hello,

I'm wondering if this project is in a maintained state.
I'm thinking about giving it a try and spend some time with it as I'm looking for a HPC workload generator (benchmark). I've cloned the repo and executed `./install.sh --all` but run into a few issues like:
* [resolved] /usr/bin/cmake is cmake v2 whereas ecbuild expects cmake3.
* [resolved] download of Miniconda is saved in miniconda folder which then will not be overwritten by the Miniconda installer
* the project is built for python2 -> are there any plan to migrate to python3?
* the conda environments are not created as package versions cannot be resolved (?) properly - `Solving environment: failed`.

Thanks

**Comment by oiffrig** [comment]
Hi, thanks for your interest in Kronos.

I have just pushed the latest release 0.7.0, that has been migrated to Python 3 and includes some major refactoring on the executor. The dependency issue when creating the environment has been fixed as well.
