### ISSUE TITLE
verify README

### ISSUE THREAD

**Issue by tbugfinder** [ecmwf/kronos#3]
Hi,

would you also kindly check the steps in the README?
I've successfully built the "package" from master (python3) however the conda environment now has different name.
In addition running `kronos-format-config-exe -s` ends up in `ModuleNotFoundError: No module named 'jsonschema'`.

Thanks

**Comment by tbugfinder** [comment]
Hm, rather looks like `./install.sh --all` doesn't install all.

**Comment by oiffrig** [comment]
There was indeed a bug in ``install.sh``. Fixed in the ``develop`` branch. I have updated the README and INSTALL as well.
